### ISSUE TITLE
Support reading from stream

### ISSUE THREAD

**Issue by peterhorsley** [konstantint/PassportEye#24]
At present, the read_mrz function takes an image file name.  It would be nice if it also supported reading from a base64 encoded string, such that, for example, in a python app that already has the image in memory, it does not have to persist it to disk before calling the api.  This would give a small performance improvement in this scenario, and also make the client code a little simpler.  

Raising this issue to check if that is something you would see as useful.  If so, I would be very happy to make a PR for that.  

Thanks for your work!

**Comment by konstantint** [comment]
Obviously, `read_mrz` as well as `MRZPipeline.__init__` as well as `mrz.image.Loader.__init__`, ideally should all be accepting a stream as their first argument rather than a filename - this would certainly be my first choice for an API - you would then be free to encode/decode your image in memory or on the fly as you see fit. Unfortunately, the first step in loading the image is currently `skimage.io.imread`, which requires its first argument to be a filename. Hence `read_mrz` also takes a filename.
I suspect the reason for that is the need to auto-detect file type from the extension (otherwise you might have to provide an extra parameter, specifying the file type). On the other hand, both `PIL`s and `matplotlib`'s `open`/`read` functions (which `sklearn.io` should be using as backends) do accept file pointers and still manage to autodetect type, I think (I might be mistaken, though).

Anyway, the choice of using filenames has been further exploited in my own "PDF auto-detection" part of `Loader.__call__`, which checks whether the filename ends with `.pdf` to make its decision.

I never had the time to polish the API here or figure out whether there is any real reason why `skimage` insists on having a filename. If you manage to find a way to have everything working with a stream given as input (perhaps you'd need to provide an extra parameter, such as 'filetype' or whatnot), this would be nice. In theory, you'd only need to change `mrz.image.Loader` and, if an extra parameter is needed, add it to `MRZPipeline` and `read_mrz`.

I wouldn't have the time to dive into this at the moment, but I'd happily test and merge a working PR.

**Comment by peterhorsley** [comment]
Thanks for your detailed feedback, you are right a stream is the best choice for this.  I've made a PR now, and added some tests.  Please review when you have time :)

**Comment by konstantint** [comment]
Merged and fixed-up in a couple of places. Will push to PyPI as v 1.3.0 soon.
