### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by getcontrol** [konstantint/PassportEye#32]
Where can we find the provided Docker image ?

**Comment by konstantint** [comment]
What docker image?

**Comment by getcontrol** [comment]
p.9 of https://buildmedia.readthedocs.org/media/pdf/passporteye/latest/passporteye.pdf

On launching server/index.py (**or using our provided Docker image**), PassportEye is going to run as a service on 5000
port, exposing an API that can be used from your services to verify documents. The API is documented here.

**Comment by konstantint** [comment]
Oh, I did not write that (nor did I register a readthedocs site for the project, in fact).

This seems to come from development in [this fork](https://github.com/CRImier/PassportEye/tree/server). I don't see any Dockerfiles there, however. I guess @CRImier might know something about them.

**Comment by CRImier** [comment]
Ah, indeed. That was written during a hackathon in 2017 - I think a Docker image was never released since the hackathon team stopped their work, and the documentation was written in "what we're going to have" fashion, not "what we have at the moment". Sorry to disappoint! Also, @konstantint the passporteye readthedocs project belongs to me - let me know if I should point it to another repo, transfer it somehow, or just disable it.

**Comment by konstantint** [comment]
@CRImier Although I feel that for now PassportEye can be documented in full within a single page (that's why I did not care to register any fancy readthedocs sites), once you've set it up, perhaps it would make sense to merge the docs/ directory into this branch as well and give me access to update the readthedocs site as well. I will try to find time for that next weekend or so. Perhaps you could transfer the readthedocs handling to me as well then (one simple way is to set up a temporary password and mail it to kt@ut.ee, for example).
