### ISSUE TITLE
Lots of zombies left behind

### ISSUE THREAD

**Issue by lauri-elevant** [konstantint/PassportEye#33]
```
PID      COMM
17748    /usr/local/bin/python /usr/local/bin/mrz --json /tmp/passport
17752    \_ /usr/local/bin/python -c from multiprocessing.semaphore_tracker import main;main(4)
17761    \_ tesseract /tmp/tess_s4sgg0lm.bmp /tmp/tess_9qz70ro2 --psm 6 -c tessedit_char_whitelist=ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789>< -c load_system_dawg= ....
```

PID 17752 will be left in a zombie state as `[python] <defunct>` after a successful run. When run in certain environments without a competent `init` to adopt and clean up those zombies (think Kubernetes), it will be left to the program calling `mrz` to clean up those defunct grandchildren processes. I think it would be nicer for `mrz` to clean up after itself.

**Comment by konstantint** [comment]
This stems from [this issue in Joblib](https://github.com/joblib/joblib/issues/841) which propagates to PassportEye [via sklearn](https://github.com/scikit-learn/scikit-learn/issues/13100).

`sklearn` is only used to run a PCA decomposition, and there is an alternative in `numpy`. However, if I remember correctly, I resorted to `sklearn` there because it was a bit faster, and I'd therefore prefer to keep it and simply wait until Joblib or SKlearn fixes the issue.

In the meantime, try the `export JOBLIB_MULTIPROCESSING=0` workaround, perhaps.

**Comment by lauri-elevant** [comment]
Thanks for the update & workaround. We will keep an eye on those issues as well.
