### ISSUE TITLE
0_id-esp.png not working

### ISSUE THREAD

**Issue by Lechucico** [konstantint/PassportEye#37]
I'm trying to read Spanish MRZ ID card, but it's not working.

The photo is the one provided in this repository: 

![0_id-esp](https://user-images.githubusercontent.com/22009615/63324870-4201cb00-c329-11e9-8ddc-bb8e925a1a15.png)

This is what I obtain from the following command: `mrz 0_id-esp.png --json`

```
{
  "mrz_type": null,
  "valid": false,
  "valid_score": 0,
  "walltime": 0.031235933303833008,
  "filename": "0_id-esp.png"
}
```

**EDIT**
I've tested with my own Spanish ID card as a photo and his detection is completely random. Some photos simply show `mrz_type: null`, another ones show `valid_score: 5` with all data wrong and some more `valid_score: 50` with almost all data correct. It's almost the same photo (taken all with an iPhone X).

**Comment by konstantint** [comment]
Note that the names of the files in the repository start with the number, indicating the "valid_score" that the algorithm was achieving at least at some point. The fact that the file is named 0_xxx indicates that, indeed, the method fails to extract the correct data here and I did not find enough time to debug the individual steps to tune the image extraction for this image in particular.

As for photos, do note that three common problems with them, which may confuse PassportEye are:
 - Background (e.g. if you take a picture of a document on a table with some structure) is not accounted for.
 - Image size (PassportEye may fail when the image is too large or when the document takes a very small part of it)
 - Orientation. The document may be oriented sideways on the photo stored by the phone.

In order to understand the actual reasons for the failure one should try examining the individual steps of the processing pipeline and tuning them appropriately. I might find some time to deal with it myself, but most probably not within a couple of months at least.
