### ISSUE TITLE
passport eye Heroku temp file issue

### ISSUE THREAD

**Issue by hunaidkhan2000** [konstantint/PassportEye#52]
Hi ,
First of all thanks for making this awesome library . I loved how easy and awesome the library is to use. 
Recently i have create an app of passport eye using fastapi and deploying the same on Heroku server. I installed everything tesseract ocr, pytesseract but i am facing problem with tmp folder and files which passport eye uses while extracting ocr
Error message is :-

2020-06-22T06:14:29.761550+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/passporteye/util/ocr.py", line 56, in ocr
2020-06-22T06:14:29.761550+00:00 app[web.1]:     f = open(output_file_name, encoding='utf-8')
2020-06-22T06:14:29.761550+00:00 app[web.1]: **FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tess_wr1c16kz.txt'**
 
I have tried all the methods  created a tmp folder. added tmp in the path of the script but nothing seems to be working in passporteye heroku combination . Image of the error is provided below for your reference. 

![image](https://user-images.githubusercontent.com/34857371/85257056-d1649700-b482-11ea-88a7-cb48f9a0e018.png)

**Comment by konstantint** [comment]
Before the file is read, three things happen (look into `ocr/util.py`):
 - An image is written to a file in a temporary directory.
 - Tesseract binary is launched with that image file as input and another temporary file to write text to.
 - The text is read from the file.

Step 3 apparently fails due to there not being an output file. Hence either Tesseract did not write it somewhy, wrote it to a different place (could Heroku somehow chroot an executable to a different location?) or the file disappeared after it was written (could Heroku clean it up somehow)?

One way to debug the issue is to change the behaviour of the `_tempnam()` function in `util/ocr.py`. For example, try replacing it with something, which returns paths under your home directory rather than `/tmp` (I read from [here](https://stackoverflow.com/questions/19253031/heroku-how-to-write-into-tmp-directory) it might work better than `/tmp`).
Note that you can do it by simply monkey-patching the function (so that you don't need to clone the whole package). Put something like that before you make any use of the library:

```
import os
from passporteye.util import ocr as ocr_lib

orig_tempnam = ocr_lib._tempnam
def my_tempnam():
	return "/home/directory/you/know/exists/"+ os.path.basename(orig_tempnam())
ocr_lib._tempnam = my_tempnam
```

See if it helps to debug the issue.

**Comment by hunaidkhan2000** [comment]
Hi @konstantint above mentioned error solved the 1st error now i am getting error with saving image which passporteye saves image in a location  using imageio. I tried searching for similar approach but did not get any success. 
![image](https://user-images.githubusercontent.com/34857371/85985119-dfc52c80-ba07-11ea-8174-8a1fc5c0c281.png)
also while doing research i found out  heroku does not allow any file to be written in the application so that is a big flaw

**Comment by hunaidkhan2000** [comment]
I am closing this issue as after trying several things Heroku does not allow saving or create a temp file.
