### ISSUE TITLE
my image is perfect but i am getting none type error

### ISSUE THREAD

**Issue by HarshkumarDegamadiya** [konstantint/PassportEye#67]
'NoneType' object has no attribute 'to_dict'

**Comment by konstantint** [comment]
This is certainly not enough to understand the cause of your problem.

**Comment by HarshkumarDegamadiya** [comment]
![image](https://user-images.githubusercontent.com/98450599/220173932-cb266f12-42c2-4560-a85c-2f41710f07ec.png)
![93056](https://user-images.githubusercontent.com/98450599/220173977-6caf3405-b82a-4238-951c-511a939aa6dc.jpeg)
![image](https://user-images.githubusercontent.com/98450599/220174046-de346ef7-4db6-4b43-a0b7-706f3a59cdad.png)
As uou can see in my image it is clearly visible all details but still it is showing None, Can you please help me out. why is it happening? how can i takle it?

**Comment by konstantint** [comment]
Thanks for providing the image. It makes it easy to reproduce and debug the problem. It seems something is wrong in the code that extracts sub-images of the "candidate boxes": see [this colab](https://colab.research.google.com/drive/1a791vdj1ssEvVhuQ9iRGmSklae6CDab9?usp=sharing)). The culprit is most probably [this part](https://github.com/konstantint/PassportEye/blob/master/passporteye/util/geometry.py#L158-L159), which makes assumptions about skimage internals which might have changed between version 12 and 19.

I'll need to take a deeper look into this to figure out how to fix it - hope to find some time this week for it. In the meantime, any assistance is welcome - the Colab above hopefully makes it reasonably clear what needs to be fixed.

**Comment by konstantint** [comment]
I fixed the root cause of the problem so now PassportEye does detect the presence of the MRZ on the provided image and manages to extract some info (in particular doc number, birth date and expiration date). Unfortunately, it seems to fail rather badly on the surname here, due to Tesseract insisting on reading many of the <<< symbols as the letter "K". As the MRZ does not cover the name/surname with a check digit (the design decision that is still a complete mystery to me), you can't even automatically detect that those were read incorrectly or rely on those. However, Tesseract's misdetections are outside the scope of this project at the moment.
